NumPy
NumPy (Numerical Python) is a Python library used for creating and working with multi-dimensional arrays.

It is the fundamental package for scientific computing in Python.

Features of NumPy:

Provides high-performance multi-dimensional arrays.
Supports mathematical and statistical operations.
Performs calculations faster than Python lists.
Used in Data Science, Machine Learning, and AI applications.
Works efficiently with large amounts of numerical data.

Diiference Between Array and list:
  Array will support only one data type(int or string or boolean)
  List will support different data type

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5,6,7,8]


In [3]:
## to convert list to array
arr=np.array(lst)
type(arr)

numpy.ndarray

In [4]:
## to check the dimensional of the array 
arr.shape

(8,)

In [5]:
## to convert single dimensional array to two dimensinal array
## important the array size shoulb be able to make a  two dimnsional array
a=arr.reshape(4,2) ##.reshape(row,column) is used to change a single to two dimensional array
a


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:

a.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

Indexing

In [9]:
#Accesiing elements in the array
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
a[0,1] # 2D array element acessing

2

In [15]:
#to acess all the elements in the array
a[:,:]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
a=[[1,2,3,4],[3,4,5,6],[7,8,9,3]]
a=np.array(a)
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 3]])

In [ ]:
# a[row_start:row_ end, col_start:col_end]
print(a[1:2,0:2]) 
print(a[2:3,2:4]) # here we have [2:3] but the row index fro 0,1,2 that means stop before 3 that means actually 2 

[[3 4]]
[[9 3]]


In [ ]:
#now example we have to take 9 only
a[2:3,2:3]
# showing in writting that means a[start from row2:stop before row2,start from 2 index stop before 4 index]


array([[9]])

INBUILT FUNCTION

In [ ]:
#np.arange(start,end,step) this is used to create an array to the range

arr=np.arange(0,10)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#using step example arange()
w=np.arange(0,11,2)
w

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#linspace(start,stop,step) -->here step is numbers quantity
#linspace is used  to generate numbers that are evenly spaced from start to end
arr=np.linspace(1,10,100)
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [59]:
#copy function 
arr=[1,2,3,4,5,6,7,8,9]
arr=np.array(arr)
arr[3:]=100
# copy of the array
arr1=arr.copy()
arr1 
  

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [66]:
# The main use of copy() function is if we give = then two arrays are pointing same varible
# Then if you make changes in one variable the other variable also changes that is why we use copy
x=[1,2,3,4,5]
s=x
print("The original array: ",x) 
s[2]=100
print("Modified array: ",s)
print("Modified original array: ",x)
#this is why we use copy 
d=x.copy()
print("Copied array: ",d)
d[1]=234 #The change does not affect the original array
print("The original array: ",x)
print("the change of copy: ",d)

The original array:  [1, 2, 3, 4, 5]
Modified array:  [1, 2, 100, 4, 5]
Modified original array:  [1, 2, 100, 4, 5]
Copied array:  [1, 2, 100, 4, 5]
The original array:  [1, 2, 100, 4, 5]
the change of copy:  [1, 234, 100, 4, 5]


In [79]:
#some conditional very useful in EDA 
arr =[1,2,3,4,5,6,7,8,9,10]
arr=np.array(arr)
val=2
arr<5
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [78]:
# create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# ones np.ones() --> used to create ones 
np.ones(5) #this will comes data type 

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,5),dtype=int) #dtype is used to change the datatype #teo dimensional array 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#random distribution
np.random.rand(3,3)

#statistics 

array([[0.32300923, 0.83025915, 0.59108806],
       [0.59115577, 0.18202415, 0.56618016],
       [0.74819056, 0.70044526, 0.90063201]])